// Code generated by entc, DO NOT EDIT.

package ent

import (
	"dedalusrpg.com/ent/schema"
	"dedalusrpg.com/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescSurname is the schema descriptor for surname field.
	userDescSurname := userFields[2].Descriptor()
	// user.DefaultSurname holds the default value on creation for the surname field.
	user.DefaultSurname = userDescSurname.Default.(string)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[3].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescPhoneNumber is the schema descriptor for phone_number field.
	userDescPhoneNumber := userFields[5].Descriptor()
	// user.DefaultPhoneNumber holds the default value on creation for the phone_number field.
	user.DefaultPhoneNumber = userDescPhoneNumber.Default.(string)
	// userDescDaysOff is the schema descriptor for days_off field.
	userDescDaysOff := userFields[6].Descriptor()
	// user.DefaultDaysOff holds the default value on creation for the days_off field.
	user.DefaultDaysOff = userDescDaysOff.Default.(string)
}
